### PR TITLE
- Updated scenario parametrs for calibartion'

### PR DESCRIPTION
**Pull request by MelchiorUU**
- fixxed "no workplaces available" error
- Sick employees still get paid.
- lowered the "extra cost" for rich peopl buying from non-essential shops
- lowered "minimum amount of cash to retain" from essential shops so they don't go instantly broke on harder times.

### CODE REVIEW

**Comment by MelchiorUU** [comment]
Added things needed for bigger/more runs through behavior space. Is this good enough to do those runs?

**Comment by rmellema** [comment]
It is good enough to do those runs, but you also need to make sure they work on your local machine. For example, I tried to run the economy behaviourspace, and the `r0` reporter gives a division by zero error in the economy baseline preset. So I cannot send this off to the supercomputer now.

**Comment by MelchiorUU** [comment]
Ah, explains my error that I got during this nights run at home. How to solve this? The problem never comes up with you do a normal run of that scenario.

Only difference that I saw was that I still have 800 ticks for the runs, I normally do 400 max. I’ll retry a normal run with 800.

--Alexander

**Comment by rmellema** [comment]
The error doesn't come up when you do a normal run because then the `r0` monitor just says "N/A" instead of throwing an error (for some reason). If you don't intent to use the r0 parameter the easiest thing is to just remove it, otherwise you need to pick a default value for r0 when there are no infections and report that instead.

**Pull request merged**
